Opetushallitus/heratepalvelu

- src/oph/heratepalvelu/amis/UpdatedOpiskeluoikeusHandler.clj
- test/oph/heratepalvelu/UpdatedOpiskeluoikeusHandler_test.clj
Loggaa, jos viestiä ei lähetetä väärän tilan (muu kuin valmistunut tai läsnä) takia. Yksikkötestit on myös luotu.
> Yksikkötestaus ja loggaaminen tilan tarkistukseen

- src/oph/heratepalvelu/external/arvo.clj
- src/oph/heratepalvelu/external/elisa.clj
- src/oph/heratepalvelu/tep/tepSmsHandler.clj
- test/oph/heratepalvelu/tepSmsHandler_test.clj
EH-1204
* Error handling on parannettu:
- Erroreja ei enää heitetä Lambdan handlerista
- Error-tilanteita logataan selkeämmin erityisesti elisa/send-tep-sms -funktiossa
- Client ja server erroreja erotetaan nyt oikein (ne olivat alun perin toisinpäin)
* Puhelinnumerot hyväksytään myös, jos puhelinnumerokirjasto ei voi päätä, ovatko ne mobiililaitteita vai kiinteitä puhelimia eli FIXED_LINE_OR_MOBILE-tyyppi nyt hyväksytään. Tämä mahdollistaa eräiden ulkomaalaisten puhelimien käytön. 
* Ei enää logata henkilökohtaisia tietoja kuten puhelinnumerot.
> Parantaa tep handler virheet

- src/oph/heratepalvelu/tpk/tpkNiputusHandler.clj
Tehdään vain yksi scan per ajo, jotta timeoutiin ei jouduta. Tämä lyhenee funktion ajoajan vain parilla minuutilla.
> Timeout-ratkaisu

- src/oph/heratepalvelu/tep/jaksoHandler.clj
Ei tallenneta työpaikkajaksoa TEP-kantaan, jos sen viimeisen keskeytymisajanjakson päättymispäivä ja työpaikkajakson loppupäivämäärä ovat samoja.
> Jaksoa ei luoda, jos keskeytynyt viimeisenä päivänä

- src/oph/heratepalvelu/common.clj
- src/oph/heratepalvelu/tep/jaksoHandler.clj
- test/oph/heratepalvelu/tep/jaksoHandler_test.clj
- test/oph/heratepalvelu/test_util.clj
Jos timestampia ei annettu, check-organisaatio-whitelist? -funktio palautti aina true (ainakin 6.30.2021 jälkeen). Poistin sen noista paikoista, joissa se oli turha.
> Poistettu yksi pouli check-organisaatio-whitelist? -funktiota

- cdk/lib/tpk.ts
Kommentoidaan arkistointifunktio pois, kun niitä ei kaytetä. Jokainen asennettu funktio maksaa.
> Kommentoitu pois arkistointifunktio

- src/oph/heratepalvelu/common.clj
Koska AMIS-herätteet lähetetään usein monta kertaa (retry-logiikan takia), muutan logituksen näin, että duplikaattiherätteet logitetaan INFO-tasolla, eikä WARN-tasolla.
> Logitus: WARN > INFO kun AMIS heräte on duplikoitu

- src/oph/heratepalvelu/amis/AMISherateEmailHandler.clj
Muokkasin virhekäsittelyn näin, että jos Arvo palauttaa virheen, funktio kaatuu. Käytännössä tämä tarkoittaa, että jos Arvo kaatuu ja palauttaa säännöllisesti virheitä, AMISherateEmailHandler yrittää käsitellä vain yhden herätteen joka kerta, kun se herää (5 minuuti välein). Tällä vältetään spämmittämistä muita palveluja, erityisesti CAS.
Vaikka Arvo-kutsut eivät käytä CASia, arvo/build-arvo-request-body tekee joitakin kutsuja muihin palveluihin, mukaan lukien ehoksiin (mikähän käyttää CASia).
> Kaada AMISherateEmailHandler, jos Arvo on nurin

- cdk/lib/tep.ts
- src/oph/heratepalvelu/external/ehoks.clj
- src/oph/heratepalvelu/tep/ehoksTimedOperationsHandler.clj
- test/oph/heratepalvelu/integration_tests/tep/ehoksTimedOperationsHandler_i_test.clj
- test/oph/heratepalvelu/tep/ehoksTimedOperationsHandler_test.clj
Teknisesti tämä toimii niin, että kun timedOperationsHandler ajetaan ajastetusti (tunnin tai parin välein), niin se kutsuu ehoksia, joka poistaa yhteystiedot ensin ehoksin kannasta ja palauttaa sitten palautettujen rivien id:t, joiden perusteella timedOperationsHandler sitten poistaa yhteystiedot herätepalvelun kannasta.
> OY-3959: Poista työpaikkaohjaajan yhteystiedot

- cdk/lib/amis.ts
- src/oph/heratepalvelu/amis/AMISehoksTimedOperationsHandler.clj
- src/oph/heratepalvelu/external/ehoks.clj
- test/oph/heratepalvelu/amis/AMISehoksTimedOperationsHandler_test.clj
- test/oph/heratepalvelu/integration_tests/amis/AMISehoksTimedOpsHandler_i_test.clj
Toimii vastaavalla tavalla kuin työpaikkaohjaajan yhteystietojen poisto, eli: Teknisesti tämä toimii niin, että kun amisTimedOperationsHandler ajetaan ajastetusti (tunnin tai parin välein), niin se kutsuu ehoksia, joka poistaa yhteystiedot ensin ehoksin kannasta ja palauttaa sitten palautettujen rivien id:t, joiden perusteella amisTimedOperationsHandler sitten poistaa yhteystiedot herätepalvelun kannasta.
> OY-3960: Opiskelijan yhteystietojen poisto

- cdk/lib/tep.ts
- src/oph/heratepalvelu/tep/kestojenUudelleenlaskentaHandler.clj
Tämä vaatii toimiakseen alle https://github.com/Opetushallitus/heratepalvelu/pull/213.
Idea on, että lambdaa operoidaan samaan tyyliin kuin tpkNiputusHandleria tai tpkArvoCallHandleria, eli AWS:n Consolesta ajellaan kertaluontoisesti. Kts. referenssiksi [dokumentaatio edellä mainituista](https://github.com/Opetushallitus/heratepalvelu/blob/master/doc/tpk.md).
Lambda hakee siis skannaamalla joukon nippuja, jonka jaksoille kestojen uudelleenlaskentaa ei ole suoritettu. Hakukriteerit ovat tosiaan seuraavat
- kuuluu nykyiseen rahoituskauteen (`niputuspvm >= "2022-07-01"`) **ja**
- uudelleenlaskentaa ei ole tehty nipun jaksoille (ts. nipun tiedoista ei löydy kenttää `kestojen-uudelleenlaskenta-suoritettu`)
Kun on löydetty joukko nippuja, nipuista valitaan **vain jaksot joille on jo laskettu …
> Lambda meneillään olevalla rahoituskaudella päättyneiden työpaikkajaksojen kestojen uudelleenlaskentaan

- src/oph/heratepalvelu/amis/AMISherateHandler.clj
- src/oph/heratepalvelu/amis/UpdatedOpiskeluoikeusHandler.clj
- src/oph/heratepalvelu/common.clj
- src/oph/heratepalvelu/tep/jaksoHandler.clj
- src/oph/heratepalvelu/tep/niputusHandler.clj
- src/oph/heratepalvelu/tep/rahoitusLaskentaHandler.clj
- test/oph/heratepalvelu/amis/AMISherateHandler_test.clj
- test/oph/heratepalvelu/amis/UpdatedOpiskeluoikeusHandler_test.clj
- test/oph/heratepalvelu/common_test.clj
- test/oph/heratepalvelu/log/logging_test.clj
- test/oph/heratepalvelu/tep/jaksoHandler_test.clj
- test/oph/heratepalvelu/tep/niputusHandler_test.clj
- test/oph/heratepalvelu/test_util.clj
Joitakin funktioita nimetty uudelleen, koska ennestään osa funktioiden nimistä ei suoraan kertonut mitä funktio tekee, ja osa teki juuri päinvastaista mitä nimen perusteella voisi olettaa.
> Funktioiden uudelleenimeämisiä

- src/oph/heratepalvelu/tep/jaksoHandler.clj
- src/oph/heratepalvelu/tep/rahoitusLaskentaHandler.clj
- test/oph/heratepalvelu/tep/jaksoHandler_test.clj
fix and rename last-keskeytymisajanjakso-has-ended?
EH-1503
> Fix logic error preventing vastaajatunnus for työpaikkajakso with no keskeytymisajanjakso

- src/oph/heratepalvelu/tpk/tpkNiputusHandler.clj
- test/oph/heratepalvelu/integration_tests/tpk/tpkNiputusHandler_i_test.clj
- test/oph/heratepalvelu/tpk/tpkNiputusHandler_test.clj
Kuvaus muutoksista:
Korjattu bugi, jonka vuoksi TPK-kyselylinkkejä on muodostunut keskeytyneille jaksoille: https://jira.eduuni.fi/browse/EH-1421
Tehty lisätarkistus: Ei niputeta jaksoa TPK-nippuun, jos tältä puuttuu kyselylinkki/vastaajatunnus.
> EH-1421: Korjattu TPK-kyselylinkkien muodostusbugi

- src/oph/heratepalvelu/external/cas_client.clj
- src/oph/heratepalvelu/external/http_client.clj
- test/oph/heratepalvelu/external/cas_client_test.clj
- test/oph/heratepalvelu/external/http_client_test.clj
Kun herätepalvelu tekee ulkoisia HTTP-kutsuja, ne voivat epäonnistua monista ennalta arvaamattomista syistä.  Tämä PR tekee kaksi asiaa:
1. lisää toimintavarmuutta kokeilemalla kutsua uudelleen silloin, kun virhe saattaa olla väliaikaista laatua.
2. helpottaa virheenselvittelyä lokittamalla aina kutsun epäonnistuessa, mitä kutsua oltiin tekemässä.
https://jira.eduuni.fi/browse/EH-1479
> Uusinta- ja raportointilogiikka kaikkiin HTTP-kyselyihin

- src/oph/heratepalvelu/amis/AMISDeleteTunnusHandler.clj
- src/oph/heratepalvelu/amis/AMISEmailResendHandler.clj
- src/oph/heratepalvelu/amis/AMISMuistutusHandler.clj
- src/oph/heratepalvelu/amis/AMISSMSHandler.clj
- src/oph/heratepalvelu/amis/AMISherateEmailHandler.clj
- src/oph/heratepalvelu/amis/EmailStatusHandler.clj
- src/oph/heratepalvelu/common.clj
- src/oph/heratepalvelu/tep/EmailMuistutusHandler.clj
- src/oph/heratepalvelu/tep/SMSMuistutusHandler.clj
- src/oph/heratepalvelu/tep/StatusHandler.clj
- src/oph/heratepalvelu/tep/ehoksTimedOperationsHandler.clj
- src/oph/heratepalvelu/tep/emailHandler.clj
- src/oph/heratepalvelu/tep/jaksoHandler.clj
- src/oph/heratepalvelu/tep/niputusHandler.clj
- src/oph/heratepalvelu/tep/rahoitusLaskentaHandler.clj
- src/oph/heratepalvelu/tep/tepSmsHandler.clj
- src/oph/heratepalvelu/tpk/tpkArvoCallHandler.clj
- src/oph/heratepalvelu/tpk/tpkNiputusHandler.clj
- test/oph/heratepalvelu/amis/AMISMuistutusHandler_test.clj
- test/oph/heratepalvelu/amis/AMISSMSHandler_test.clj
- test/oph/heratepalvelu/amis/AMISherateEmailHandler_test.clj
- test/oph/heratepalvelu/amis/EmailStatusHandler_test.clj
- test/oph/heratepalvelu/common_test.clj
- test/oph/heratepalvelu/tep/EmailMuistutusHandler_test.clj
- test/oph/heratepalvelu/tep/SMSMuistutusHandler_test.clj
- test/oph/heratepalvelu/tep/StatusHandler_test.clj
- test/oph/heratepalvelu/tep/emailHandler_test.clj
- test/oph/heratepalvelu/tep/niputusHandler_test.clj
- test/oph/heratepalvelu/tep/tepSmsHandler_test.clj
- test/oph/heratepalvelu/test_util.clj
Jotta virhetilanteet eivät aiheuttaisi koskaan handlerin jumittumista, tämä PR uudelleenstrukturoi koodin siten, ettei yhden handlerin suorituskerran aikana koskaan haeta tietokannasta samaa tietuetta useampaa kertaa.  Tämä avaa virheenkäsittelyyn uuden mahdollisuuden, että virhe vain lokitetaan ja jätetään huomiotta, ja siirrytään seuraavaan tietueeseen.
https://jira.eduuni.fi/browse/EH-1519
> Ei koskaan tehdä silmukassa samaa DDB-kyselyä uudestaan

- cdk/lib/amis.ts
- cdk/lib/heratepalvelu.ts
- cdk/lib/tep.ts
- cdk/lib/tpk.ts
Lisätään metric filterit pitämään kirjaa ERROR-lokitusten lukumääristä lokeissa. Vastaavanlaisia metric filtereitä löytyy jo muiden Opintopolun palveluiden lokiryhmistä, mutta nämä puuttuvat kaikista Herätepalveun lambdojen lokiryhmistä. Näiden metric filtereiden lisääminen on edellytys sille, että voidaan nostaa näitä ERROR-lukumäärämetriikoita näkymiin dashboardille, ja tarvittaessa myös nostamaan hälyjä niiden perusteella.
https://jira.eduuni.fi/browse/EH-1471
> Add metric filters to lambda log groups

- cdk/lib/amis.ts
- src/oph/heratepalvelu/amis/AMISCommon.clj
- src/oph/heratepalvelu/common.clj
- src/oph/heratepalvelu/tep/jaksoHandler.clj
- src/oph/heratepalvelu/tep/rahoitusLaskentaHandler.clj
- src/oph/heratepalvelu/util/dbChanger.clj
- test/oph/heratepalvelu/amis/AMISCommon_test.clj
- test/oph/heratepalvelu/integration_tests/amis/AMISherateHandler_i_test.clj
- test/oph/heratepalvelu/integration_tests/amis/UpdatedOpiskeluoikeusHandler_i_test.clj
- test/oph/heratepalvelu/integration_tests/tep/jaksoHandler_i_test.clj
- test/oph/heratepalvelu/tep/jaksoHandler_test.clj
https://jira.eduuni.fi/browse/EH-1406
Aiemmin rahoitusryhmä poistettiin Arvoon lähetettävistä tiedoista, nyt siivotaan sen päättely ja tallentaminen pois myös Herätepalvelusta.
Tämän lisäksi tehdään Python-skripti, joka poistaa kantaan jo tallennetut rahoitusryhmätiedot. EDIT: Tässä voidaakin käyttää Severin [aiemmin tekemää](https://jira.eduuni.fi/secure/attachment/57761/57761_ddb-rm-attr-from-all-items.py) skriptiä rahoitusryhma-kentän poistamiseen.
> EH-1406: Lopeta rahoitusryhmän päättely ja tallentaminen

- cdk/lib/tpk.ts
https://jira.eduuni.fi/browse/EH-1578
Ajastukset ovat nyt oletuksena pois päältä ja ne voidaan laittaa päälle lähempänä ajankohtaa, jos katsotaan että automaatiota halutaan käyttää. Muussa tapauksessa ajot voi ajaa kuten ennenkin.
QA:n AWS-konsolista voi käydä katsomassa, missä ajankohdissa säännöt ovat menossa ajoon. Esim:
* TPKArvoCallHandlerDefault
* Next 10 trigger date(s)
* Mon, 04 Dec 2023 06:05:00 UTC
* Mon, 04 Dec 2023 06:25:00 UTC
* Mon, 04 Dec 2023 06:45:00 UTC
* Mon, 04 Dec 2023 07:05:00 UTC
* Mon, 04 Dec 2023 07:25:00 UTC
* Mon, 04 Dec 2023 07:45:00 UTC
* Mon, 04 Dec 2023 08:05:00 UTC
* Mon, 04 Dec 2023 08:25:00 UTC
* Mon, 04 Dec 2023 08:45:00 UTC
* Mon, 04 Dec 2023 09:05:00 UTC
> EH-1578: Automatisoidaan TPK-kyselylinkkien muodostusajot

- src/oph/heratepalvelu/tep/jaksoHandler.clj
- test/oph/heratepalvelu/tep/jaksoHandler_test.clj
https://jira.eduuni.fi/browse/EH-1579
Siivotaan työpaikan nimi ennen DynamoDB:hen tallentamista, jolloin ei saada jatkossa epämääräisiä alaviivalla `_` alkavia tai päättyviä normalisoituja nimiä.
Nimien ja normalisoitujen nimien takautuva korjaus tehdään erillisellä skriptillä.
> Trim työpaikan nimi before saving heräte to DynamoDB

- src/oph/heratepalvelu/common.clj
- test/oph/heratepalvelu/common_test.clj
Heijastuu eHOKSiin siirrettyyn toiminnallisuuteen: https://github.com/Opetushallitus/ehoks/pull/620
> EH-1683: poistetaan rahoituskauden viimeisen niputuksen erikoiskäsittely

- cdk/lib/tep.ts
- src/oph/heratepalvelu/tep/contactInfoCleaningHandler.clj
- src/oph/heratepalvelu/tep/ehoksTimedOperationsHandler.clj
- test/oph/heratepalvelu/integration_tests/tep/contactInfoCleaningHandler_i_test.clj
- test/oph/heratepalvelu/tep/contactInfoCleaningHandler_test.clj
- test/oph/heratepalvelu/tep/ehoksTimedOperationsHandler_test.clj
timedOperationsHandler-lambda epäonnistui timeouteihin ja aiheutti ongelmia mm. työpaikkajaksojen käsittelyssä (kts. Slack-keskustelu https://opetushallitus.slack.com/archives/C03JN1DGD53/p1717587552619319?thread_ts=1717571706.223229&cid=C03JN1DGD53). Tein uuden lambdan työpaikkaohjaajien yhteystietojen siivoamiselle.
https://jira.eduuni.fi/browse/EH-1514
> EH-1686: Create new lambda for contact info cleaning

- cdk/lib/amis.ts
- cdk/lib/heratepalvelu.ts
- cdk/lib/tep.ts
- cdk/lib/tpk.ts
Virheiden lukumääriä seuraavat metriikat `amis`, `tep` ja `tpk` lokiryhmille: https://jira.eduuni.fi/browse/EH-1693
> Add error metric filters for `amis`, `tep`, and `tpk` log groups

- cdk/lib/tep.ts
- src/oph/heratepalvelu/tep/jaksoHandler.clj
- test/oph/heratepalvelu/integration_tests/tep/jaksoHandler_i_test.clj
- test/oph/heratepalvelu/tep/jaksoHandler_test.clj
Yksilöivä tunniste tallentumaan Herätepalveluun. Käytetään jaksojen yksilöintiin hankkimistapa ID:n sijasta HOKS ID:tä ja jakson yksilöivää tunnistetta.
https://jira.eduuni.fi/browse/EH-1697
> EH-1697: Työpaikkajakson yksilöivä tunniste tallentumaan Herätepalveluun

- project.clj
- src/oph/heratepalvelu/tep/niputusHandler.clj
- test/oph/heratepalvelu/integration_tests/tep/niputusHandler_i_test.clj
- test/oph/heratepalvelu/tep/niputusHandler_test.clj
EH-1699 muutosten myötä, Herätepalvelussa aletaan käyttämään jaksojen yksilöintiin (hoks_id, yksiloiva_tunniste)-kombinaatiota. Ennen näiden muutosten asentamista QA:lle tai tuotantoon, on tehtävä ensin eHOKS-asennus PR:n https://github.com/Opetushallitus/ehoks/pull/639 muutoksista.
https://jira.eduuni.fi/browse/EH-1699
> EH-1699: Use hoks id & yksiloiva id instead of hankkimistapa id when computing kestot

- cdk/lib/tep.ts
- src/oph/heratepalvelu/tep/kestojenUudelleenlaskentaHandler.clj
- src/oph/heratepalvelu/tep/niputusHandler.clj
~~Minimaaliset päivitykset aiempaan kestonlaskenta-lambdan toteutukseen. Vanhan toteutuksen PR: https://github.com/Opetushallitus/heratepalvelu/pull/217~~
~~https://jira.eduuni.fi/browse/EH-1549~~
Tiketissä [EH-1699](https://jira.eduuni.fi/browse/EH-1699) korjattiin kestonlaskentalogiikka käyttämään hankkimistapa id:n sijasta HOKS id:tä ja yksilöivää tunnistetta. Tässä on laadittu lambda, joka suorittaa kestojen uudelleenlaskennan takautuvasti edellisen ja meneillään olevan rahoituskauden jaksoille.
https://jira.eduuni.fi/browse/EH-1700
> EH-1700: Lambda työpaikkajaksojen kestojen uudelleenlaskentaan takautuvasti

- src/oph/heratepalvelu/tep/kestojenUudelleenlaskentaHandler.clj
https://jira.eduuni.fi/browse/EH-1700
> EH-1700: Give zero duration if jakso is not found from eHOKS

- src/oph/heratepalvelu/common.clj
- src/oph/heratepalvelu/tep/jaksoHandler.clj
- src/oph/heratepalvelu/tep/rahoitusLaskentaHandler.clj
- src/oph/heratepalvelu/tpk/tpkNiputusHandler.clj
- src/oph/heratepalvelu/util/string.clj
- test/oph/heratepalvelu/util/string_test.clj
Poistetaan alaviivat työpaikkajaksojen normalisoitujen nimien alusta ja lopusta. Lisätty testejä.
https://jira.eduuni.fi/browse/EH-1747
> Remove underscore prefixes and postfixes from normalized names

- src/oph/heratepalvelu/amis/AMISCommon.clj
- src/oph/heratepalvelu/amis/AMISherateEmailHandler.clj
- src/oph/heratepalvelu/amis/AMISherateHandler.clj
- src/oph/heratepalvelu/amis/UpdatedOpiskeluoikeusHandler.clj
- src/oph/heratepalvelu/common.clj
- src/oph/heratepalvelu/external/arvo.clj
`:ehoks-id` -> `:ehoks_id` kentän nimenmuutoksella olikin sen verran vaikutusta, että tieto opiskelijapalautteiden tilasta ei tällä hetkellä synkronoidu Herätepalvelusta takaisin eHOKSiin. Tässä on toteutettu tuo simppeli korjaus, että käytetään jompaa kumpaa kentän nimeä, `:ehoks-id` tai `:ehoks_id`, riippuen kumpi on olemassa. Tää on tehty kaikkialle missä `:ehoks-id`-keywordia käytetään, riippumatta siitä onko kyseessä aktiivista tai kuollutta koodia.
https://jira.eduuni.fi/browse/EH-1816
> EH-1816: Use `:ehoks-id` or `:ehoks_id`

- src/oph/heratepalvelu/amis/AMISherateEmailHandler.clj
- src/oph/heratepalvelu/common.clj
- src/oph/heratepalvelu/external/ehoks.clj
- test/oph/heratepalvelu/integration_tests/amis/AMISherateEmailHandler_i_test.clj
Koodipolku, jolla kyselylinkki luodaan, muuttui sen takia että palaute-backendista työnnetään herätepalvelun kantaan herätteitä joissa on valmiiksi kyselylinkki.  Vanhastaan olemassa ollut (mutta ilmeisesti lähes käyttämätön) fallback-koodi `send-lahetys-data-to-ehoks`-funktiossa aktivoitui, mutta ei todennäköisesti ole koskaan ollut toimivaa koodia.  Tämä PR pyrkii tekemään POST .../kyselylinkki -kutsun samaan tapaan kuin se on tehty aikoinaan ja lisäämään vähän lokitusta _ennen_ virhetilanteita.
https://jira.eduuni.fi/browse/EH-1816
> EH-1816: fix eHOKS kyselylinkki creation logic
