- cdk/lib/amis.ts
- src/oph/heratepalvelu/util/dbChanger.clj
Joistakin kyselyistä löytyy tila "tutkinnon suorittaneet", vaikka opiskelija on suorittanut vain osia tutkintoa. Luodaan funktio, jolla ne voi identifioida.
> Löydä väärät suoritustilat

- src/oph/heratepalvelu/amis/EmailStatusHandler.clj
https://jira.eduuni.fi/browse/EH-1232
> Tilaa ei päivitetä ehoksiin muistutusviestin jälkeen

- cdk/lib/amis.ts
Se tarvitaan varmasti tulevaisuudessa, mutta siitä ei kannata maksaa kun sitä ei käytetä.
> Kommentoi arkistointifunktio pois

- src/oph/heratepalvelu/external/arvo.clj
- src/oph/heratepalvelu/tep/jaksoHandler.clj
Järjestetty myös require-statementeja.
> EH-1251 - Lisätty työpaikan normalisoitu nimi Arvon POST-kutsuun

- cdk/lib/tep.ts
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.FunctionOptions.html
> Reserved concurrency rajoitettu yhteen

- src/oph/heratepalvelu/tpk/tpkNiputusHandler.clj
Haluan varmistaa, että ei tule virhettä DynamoDB:stä readien aikana.
> Lisätty logitusta

- src/oph/heratepalvelu/amis/AMISDeleteTunnusHandler.clj
- src/oph/heratepalvelu/amis/AMISEmailResendHandler.clj
- test/oph/heratepalvelu/integration_tests/amis/AMISDeleteTunnusHandler_i_test.clj
- test/oph/heratepalvelu/integration_tests/amis/AMISEmailResendHandler_i_test.clj
- test/oph/heratepalvelu/integration_tests/amis/EmailStatusHandler_i_test.clj
- test/oph/heratepalvelu/integration_tests/harness_test.clj
- test/oph/heratepalvelu/integration_tests/mock_cas_client.clj
- test/oph/heratepalvelu/integration_tests/mock_db.clj
- test/oph/heratepalvelu/integration_tests/mock_http_client.clj
- test/oph/heratepalvelu/integration_tests/parse_cond_expr.clj
DB mockattu, ja pari esimerkkitestiä lisätty. On tulossa lisää testejä seuraavassa PR:ssä.
> Integraatiotestit: osa 1

- src/oph/heratepalvelu/amis/AMISCommon.clj
- src/oph/heratepalvelu/amis/AMISDeleteTunnusHandler.clj
- src/oph/heratepalvelu/amis/AMISEmailResendHandler.clj
- src/oph/heratepalvelu/amis/EmailStatusHandler.clj
- src/oph/heratepalvelu/external/viestintapalvelu.clj
- src/oph/heratepalvelu/tep/EmailMuistutusHandler.clj
- src/oph/heratepalvelu/tep/SMSMuistutusHandler.clj
- src/oph/heratepalvelu/tep/StatusHandler.clj
- src/oph/heratepalvelu/tep/emailHandler.clj
- src/oph/heratepalvelu/tep/niputusHandler.clj
- src/oph/heratepalvelu/tep/tepCommon.clj
- src/oph/heratepalvelu/tep/tepSmsHandler.clj
- test/oph/heratepalvelu/amis/AMISCommon_test.clj
- test/oph/heratepalvelu/amis/AMISDeleteTunnusHandler_test.clj
- test/oph/heratepalvelu/amis/AMISEmailResendHandler_test.clj
- test/oph/heratepalvelu/amis/EmailStatusHandler_test.clj
- test/oph/heratepalvelu/external/viestintapalvelu_test.clj
- test/oph/heratepalvelu/tep/EmailMuistutusHandler_test.clj
- test/oph/heratepalvelu/tep/SMSMuistutusHandler_test.clj
- test/oph/heratepalvelu/tep/StatusHandler_test.clj
- test/oph/heratepalvelu/tep/emailHandler_test.clj
- test/oph/heratepalvelu/tep/niputusHandler_test.clj
- test/oph/heratepalvelu/tep/tepCommon_test.clj
- test/oph/heratepalvelu/tep/tepSmsHandler_test.clj
Olen yksinkertaistanut paljon duplikoitua koodia. Teen nämä muutokset ainakin kahtena PR:nä sen takia, että haluan olla konservatiivinen erityisesti update-nippu -funktion asentamisessa.
> OY 3383 - osa 1

- src/oph/heratepalvelu/tep/StatusHandler.clj
- src/oph/heratepalvelu/tep/niputusHandler.clj
- src/oph/heratepalvelu/tep/tepCommon.clj
- test/oph/heratepalvelu/tep/StatusHandler_test.clj
- test/oph/heratepalvelu/tep/niputusHandler_test.clj
- test/oph/heratepalvelu/tep/tepCommon_test.clj
update-nippu vähän laajempaan käyttöön; cond-expr takaisin
> Oy 3383 osa 2

- README.md
- doc/amis.md
- doc/asennukset.md
- doc/external.md
- doc/misc.md
Tämä ei ole edes läheskään valmis, mutta halusin saada ensimmäisen osan reviewin läpi mahdollisimman pian.
> Jonkin verran dokumentaatiota lisätty

- src/oph/heratepalvelu/amis/AMISCommon.clj
- src/oph/heratepalvelu/amis/AMISEmailResendHandler.clj
- src/oph/heratepalvelu/amis/AMISMuistutusHandler.clj
- src/oph/heratepalvelu/amis/AMISherateEmailHandler.clj
- src/oph/heratepalvelu/amis/EmailStatusHandler.clj
- src/oph/heratepalvelu/amis/UpdatedOpiskeluoikeusHandler.clj
- src/oph/heratepalvelu/common.clj
- src/oph/heratepalvelu/tep/EmailMuistutusHandler.clj
- src/oph/heratepalvelu/tep/SMSMuistutusHandler.clj
- src/oph/heratepalvelu/tep/emailHandler.clj
- src/oph/heratepalvelu/tep/niputusHandler.clj
- src/oph/heratepalvelu/tep/tepCommon.clj
- src/oph/heratepalvelu/tep/tepSmsHandler.clj
- test/oph/heratepalvelu/amis/AMISCommon_test.clj
- test/oph/heratepalvelu/amis/AMISEmailResendHandler_test.clj
- test/oph/heratepalvelu/amis/AMISMuistutusHandler_test.clj
- test/oph/heratepalvelu/amis/AMISherateEmailHandler_test.clj
- test/oph/heratepalvelu/amis/EmailStatusHandler_test.clj
- test/oph/heratepalvelu/common_test.clj
- test/oph/heratepalvelu/tep/EmailMuistutusHandler_test.clj
- test/oph/heratepalvelu/tep/SMSMuistutusHandler_test.clj
- test/oph/heratepalvelu/tep/emailHandler_test.clj
- test/oph/heratepalvelu/tep/tepSmsHandler_test.clj
Enemmän yksinkertaistamista/refaktorointia
> OY 3383 osa 3

- cdk/lib/tep.ts
- src/oph/heratepalvelu/tep/niputusHandler.clj
- src/oph/heratepalvelu/util/supplementaryNiputus.clj
Olen viime viikon perjantaina tehnyt virheen jaksoHandler-funktiossa, jonka takia jotkut nippurivit ovat jääneet muodostumatta tietokannassa. Tämä korjaa ongelman.
Tämä kannattaa tarkistaa tosi huolellisesti, koska se muuttaa tietoja tuotantotietokannassa. Olen testannut sen peusteellisesti, mutta bugi voi aina jäänyt huomaamatta.
> Fix jakso handler error

- cdk/lib/amis.ts
Tää ei tarvitse oikeuksia tonne tauluun.
> Poistetaan turhat oikat ONR funktiolta

- cdk/lib/tep.ts
- src/oph/heratepalvelu/util/dbChanger.clj
- jaksotunnus-taulun siivous lambdan kautta
> EH-1408: jälkityöt

- cdk/lib/amis.ts
Funktio tarvitseekin SSM oikat.
> Fix ONRHandlerin oikeudet

- doc/amis.md
- doc/virheet.md
> Dokumentaatiota

- .github/workflows/build.yml
- src/oph/heratepalvelu/amis/AMISCommon.clj
- src/oph/heratepalvelu/amis/AMISherateHandler.clj
- src/oph/heratepalvelu/amis/UpdatedOpiskeluoikeusHandler.clj
- src/oph/heratepalvelu/common.clj
- test/oph/heratepalvelu/amis/AMISCommon_test.clj
- test/oph/heratepalvelu/amis/AMISherateHandler_test.clj
- test/oph/heratepalvelu/amis/UpdatedOpiskeluoikeusHandler_test.clj
- test/oph/heratepalvelu/common_test.clj
- test/oph/heratepalvelu/log/logging_test.clj
- test/oph/heratepalvelu/test_util.clj
Lisätty lokitus, mitä herätettä käsitellään, sekä tieto siitä, miksi sitä ei tallenneta.  Loput ovat lähinnä nimien refaktorointeja nimeämiskäytäntöjen mukaisiksi.
> Refactorings and logging improvements to -handleAMISherate

- .github/workflows/build.yml
- src/oph/heratepalvelu/amis/EmailStatusHandler.clj
- src/oph/heratepalvelu/external/viestintapalvelu.clj
- src/oph/heratepalvelu/tep/StatusHandler.clj
- test/oph/heratepalvelu/amis/EmailStatusHandler_test.clj
- test/oph/heratepalvelu/external/viestintapalvelu_test.clj
Olennaisin muutos on se, että nyt lokitetaan jokainen heräte, joka käsitellään, ja myös käsittelyn onnistuminen.  Muut muutokset ovat koodin jakamista pienempiin funktioihin ja funktioiden uudelleennimeämisiä.
> Refactorings and logging improvements to -handleEmailStatus

- src/oph/heratepalvelu/amis/AMISherateEmailHandler.clj
- src/oph/heratepalvelu/external/arvo.clj
- src/oph/heratepalvelu/util/ONRDLQresendHandler.clj
- src/oph/heratepalvelu/util/ONRhenkilomodify.clj
- test/oph/heratepalvelu/integration_tests/amis/AMISherateEmailHandler_i_test.clj
- myös muutamalle muulle handlerille (ONRDLQresendHandler ja handleONRhenkilomodify) lokitusparannuksia
- pyritty noudattamaan periaatetta: lokita kaikki tilanteet, ota kiinni ja lokita kaikki poikkeukset (handleSendAMISEmails osaa kumminkin yrittää uudestaan)
- refaktorointien tarkoitus on vähentää funktioiden pituutta ja sisennysmäärää
> Refactorings and logging improvements to -handleSendAMISEmails

- .github/workflows/build.yml
- src/oph/heratepalvelu/amis/AMISCommon.clj
- src/oph/heratepalvelu/amis/AMISDeleteTunnusHandler.clj
- src/oph/heratepalvelu/amis/AMISEmailResendHandler.clj
- src/oph/heratepalvelu/amis/AMISMuistutusHandler.clj
- src/oph/heratepalvelu/amis/AMISSMSHandler.clj
- test/oph/heratepalvelu/amis/AMISCommon_test.clj
- test/oph/heratepalvelu/amis/AMISDeleteTunnusHandler_test.clj
- test/oph/heratepalvelu/amis/AMISEmailResendHandler_test.clj
- test/oph/heratepalvelu/amis/AMISSMSHandler_test.clj
Jälleen, monissa paikoissa jaettu funktioita pienemmiksi ja vähennetty sisennystä.  Lisäksi varsinaiset lokien lisäyksetkin ovat mukana.
> Refactorings and logging improvements to -handleAMISSMS, -handleEmailResend, and -handleSendAMISMuistutus

- src/oph/heratepalvelu/amis/UpdatedOpiskeluoikeusHandler.clj
- src/oph/heratepalvelu/common.clj
- test/oph/heratepalvelu/amis/UpdatedOpiskeluoikeusHandler_test.clj
- test/oph/heratepalvelu/integration_tests/amis/UpdatedOpiskeluoikeusHandler_i_test.clj
Hajotettu pienemmiksi funktioiksi, lisätty lokitusta, korjattu yksi bugi (tai lähinnä epäkätevyys) jonka vuoksi testien tuloksetkin vaihtuivat vähän.
> Refactorings and logging improvements to -handleUpdatedOpiskeluoikeus

- src/oph/heratepalvelu/amis/AMISherateEmailHandler.clj
Throw exceptions if we cannot update DB for kyselylinkki to avoid infinite looping
> Make exception handling back to how it was before pkalliok-EH-1451-2

- src/oph/heratepalvelu/amis/AMISehoksTimedOperationsHandler.clj
- src/oph/heratepalvelu/tep/ehoksTimedOperationsHandler.clj
- test/oph/heratepalvelu/amis/AMISehoksTimedOperationsHandler_test.clj
- test/oph/heratepalvelu/integration_tests/amis/AMISehoksTimedOpsHandler_i_test.clj
- test/oph/heratepalvelu/integration_tests/tep/ehoksTimedOperationsHandler_i_test.clj
- test/oph/heratepalvelu/tep/ehoksTimedOperationsHandler_test.clj
Tilapäisesti disabloidaan yhteystietojen poisto. Revertataan/refaktoroidaan kun muut herätepalvelun ongelmat on selvitetty.
> EH-1504: Yhteystietojen poisto pois päältä tilapäisesti

- src/oph/heratepalvelu/amis/AMISehoksTimedOperationsHandler.clj
- src/oph/heratepalvelu/tep/ehoksTimedOperationsHandler.clj
- test/oph/heratepalvelu/amis/AMISehoksTimedOperationsHandler_test.clj
- test/oph/heratepalvelu/integration_tests/amis/AMISehoksTimedOpsHandler_i_test.clj
- test/oph/heratepalvelu/integration_tests/tep/ehoksTimedOperationsHandler_i_test.clj
- test/oph/heratepalvelu/tep/ehoksTimedOperationsHandler_test.clj
This reverts commit f8c3b77c1b60375c2e055527b8c67b0d2953bac8.
> Revert "Disable old contact details deletion"

- project.clj
- src/oph/heratepalvelu/tpk/tpkArvoCallHandler.clj
- src/oph/heratepalvelu/tpk/tpkNiputusHandler.clj
- test/oph/heratepalvelu/tpk/tpkNiputusHandler_test.clj
Taas PR jossa on:
- hajotettu funktioita lyhyemmiksi
- lisätty lokitusta
- nimetty uudelleen funktioita, joiden nimi ei kerro, mitä ne palauttavat
> Refactorings and logging improvements to -handleTpkNiputus and -handleTpkArvoCalls

- src/oph/heratepalvelu/tep/jaksoHandler.clj
- test/oph/heratepalvelu/integration_tests/tep/jaksoHandler_i_test.clj
- test/oph/heratepalvelu/tep/jaksoHandler_test.clj
Poistaa käsittelystä ne työpaikkajaksot, joista osa-aikaisuus puuttuu 1.7.2023 lähtien.
https://jira.eduuni.fi/browse/EH-1469
> Drop työpaikkajakso if it doesn't have osa-aikaisuus and ends after rahoituskausi 2022

- src/oph/heratepalvelu/amis/AMISherateEmailHandler.clj
- test/oph/heratepalvelu/integration_tests/amis/AMISherateEmailHandler_i_test.clj
Tilanne on vähän marginaalinen koska se edellyttää että koulutuksen järjestäjä merkitsee keskeytyneeseen opiskeluun osaamisen saavutetuksi, mutta estetään kumminkin palautteenkeruu näissä tapauksissa.
https://jira.eduuni.fi/browse/EH-1500
> Ei kerätä palautetta keskeytyneistä opinnoista

- src/oph/heratepalvelu/external/cas_client.clj
- src/oph/heratepalvelu/external/ehoks.clj
- src/oph/heratepalvelu/external/http_client.clj
- test/oph/heratepalvelu/external/ehoks_test.clj
- test/oph/heratepalvelu/integration_tests/mock_cas_client.clj
* jos pyyntö eHoksiin palauttaa 401, haetaan uusi Service Ticket ja yritetään pyyntöä sillä uudelleen
* jos Service Ticketin haku palauttaa 404, virkistetään Ticket Granting Ticket ja yritetään Service Ticketin hakua uudelleen
> OY-4385: eHoks-pyyntöjen virheenkäsittelyn parantaminen

- cdk/lib/amis.ts
- cdk/lib/tep.ts
- cdk/lib/tpk.ts
- src/oph/heratepalvelu/amis/archiveHerateTable.clj
- src/oph/heratepalvelu/tep/archiveJaksoTable.clj
- src/oph/heratepalvelu/tep/archiveNippuTable.clj
- src/oph/heratepalvelu/tpk/archiveTpkNippuTable.clj
- test/oph/heratepalvelu/amis/archiveHerateTable_test.clj
- test/oph/heratepalvelu/integration_tests/tep/archiveJaksoTable_i_test.clj
- test/oph/heratepalvelu/integration_tests/tep/archiveNippuTable_i_test.clj
- test/oph/heratepalvelu/integration_tests/tpk/archiveTpkNippuTable_i_test.clj
- test/oph/heratepalvelu/tep/archiveJaksoTable_test.clj
- test/oph/heratepalvelu/tep/archiveNippuTable_test.clj
- test/oph/heratepalvelu/tpk/archiveTpkNippuTable_test.clj
amis- & tep-rahoituskauden 2022-23 & vanhojen tpk-kausien arkistointi
> EH-1633: arkistointi

- cdk.sh
- cdk/lib/amis.ts
- cdk/lib/tep.ts
- cdk/lib/teprah.ts
- cdk/lib/tpk.ts
- cdk/package-lock.json
- cdk/package.json
- Päivitetty aws-cdk-lib, constructs ja aws-cdk paketit
- Muunnettu logRetention -> logGroup ja luotu omat lokiryhmät per kokonaisuus
Testissä pallerolla
> Päivitetään kirjastot aws-cdk-lib ja aws-cdk sekä lisätään keskitetyt lokiryhmät

- src/oph/heratepalvelu/amis/AMISSMSHandler.clj
- src/oph/heratepalvelu/external/aws_ssm.clj
- src/oph/heratepalvelu/external/http_client.clj
This is a re-issue of #266 , which I accidentally merged to a wrong branch.
> Make local testing easier by tweaking some AWS calls to be overrideable by environment variables

- src/oph/heratepalvelu/tep/kestojenUudelleenlaskentaHandler.clj
Oiskohan tää kokeilemisen arvoinen?
https://jira.eduuni.fi/browse/EH-1700
> EH-1700: Calculate kestot one at a time in uudelleenlaskenta

- src/oph/heratepalvelu/tep/kestojenUudelleenlaskentaHandler.clj
Suoritetaan kestojen uudelleenlaskenta takautuvasti uudemman kerran koulutuksenjärjestäjälle.
https://jira.eduuni.fi/browse/EH-1734
> Recalculate kestot for a specific koulutuksenjarjestaja

- src/oph/heratepalvelu/tep/kestojenUudelleenlaskentaHandler.clj
Suoritetaan kestojen uudelleenlaskenta uudemman kerran koulutuksenjärjestäjälle.
https://jira.eduuni.fi/browse/EH-1734
> Recalculate kestot once more for specific koulutuksenjarjestaja

- src/oph/heratepalvelu/tep/kestojenUudelleenlaskentaHandler.clj
[EH-1734](https://jira.eduuni.fi/browse/EH-1734)
> Recalculate kestot for koulutuksenjarjestaja

- src/oph/heratepalvelu/amis/AMISherateEmailHandler.clj
- src/oph/heratepalvelu/amis/EmailStatusHandler.clj
- src/oph/heratepalvelu/external/arvo.clj
- test/oph/heratepalvelu/amis/EmailStatusHandler_test.clj
- test/oph/heratepalvelu/external/arvo_test.clj
- test/oph/heratepalvelu/integration_tests/amis/AMISherateEmailHandler_i_test.clj
- test/oph/heratepalvelu/integration_tests/amis/EmailStatusHandler_i_test.clj
Korjataan amiskyselyssä Arvoon lähetettävä herätepvm. 
Vastauslinkin päivitys käyttää tulevaisuudessa uutta rajapintaa, jahka se tulee Arvossa saataville: https://wiki.eduuni.fi/spaces/CscArvo/pages/328998165/Rajapintojen+tietojen+selitteet+ja+pakollisuus#Rajapintojentietojenselitteetjapakollisuus-Opiskelijapalaute:aloitus-/p%C3%A4%C3%A4tt%C3%B6kyselynvastauslinkinp%C3%A4ivitt%C3%A4minen(uusirajapinta,jokakorvaayll%C3%A4olevanmetatiedot-rajapinnan,amisEmailStatusHandlertuleek%C3%A4ytt%C3%A4m%C3%A4%C3%A4njatkossa)
https://jira.eduuni.fi/browse/EH-1457
> EH-1457: Korjataan amiskyselyssä Arvoon lähetettävä herätepvm

- src/oph/heratepalvelu/common.clj
- test/oph/heratepalvelu/common_test.clj
- test/oph/heratepalvelu/integration_tests/tep/jaksoHandler_i_test.clj
- test/oph/heratepalvelu/tep/jaksoHandler_test.clj
Asetusmuutoksen myötä niputus tehdään 1.7.2025 alkaen kerran kuussa, kuukauden ensimmäisena päivänä.
https://jira.eduuni.fi/browse/EH-1808
> EH-1808: Make niputus occur once a month
